### ISSUE TITLE
Parallel Cognate Set

### ISSUE THREAD

**Issue by kalvinchang** [clefourrier/CopperMT#1]
Hi. I was reading your thesis "Neural Approaches to Historical Word Reconstruction" and saw that you curated a large Romance dataset spanning Galician, Portuguese, Spanish, Catalan, Occitan, Italian, French, Romanian, Aromanian and Latin.

From the thesis, it seems like the historical word reconstruction dataset only contains Latin, Spanish, and Italian, and the "massive cognate prediction" dataset only contains word pairs.

I was wondering if it was possible to create a large parallel dataset of cognate sets for all 9 aforementioned Romance daughter languages and Latin from EtymDB2, though I imagine that it maybe sparse.

**Comment by clefourrier** [comment]
Hi! Thank you for reading my thesis :hugs: 

Creating cognate sets, and not cognate pairs, using EtymDB should definitely be possible.
What we did for cognate pairs was to "go back" into the history of a word, by climbing back up it's etymological tree language by language, keeping only the ancestors that followed an allowed path. 
For example for Fr, coming from Mid Fr, coming from OFr, coming from Latin, we keep all ancestors, but for Fr, coming from Italian, coming from Latin, we keep none (italian is not an allowed parent of Fr).
Then from all ancestors, we go back down the allowed children (for example: Latin to Old Spanish to Mid Spanish to Spanish).

To use this method to generate cognate sets, you have two solutions: 
- the more computationally intensive but probably more exhaustive would be to apply this same method to all language paths that interest you (go back to one ancestor for one language, then go down the other way for all other languages).
- the less computationally intensive would be to select one language as being a "reference ancestor", and from this parent, go down to all children, therefore not having to manage parsing a tree up and down.

However, where creating cognate sets for La/Es/It/Fr (probably Pt and Ro too) will be easy, I suspect that Galician, Aromanian, Catalan and Occitan are going to be limiting factors if you want your cognate sets to be full. (If you're happy with partial cognate sets then it should be just fine).

**Comment by kalvinchang** [comment]
Thanks for the detailed response!!

**Comment by clefourrier** [comment]
Good luck with your project :smile:
